version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install AWS CLI
      - pip install awscli

      # Install Terraform
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform

  pre_build:
    commands:
      # Print versions for verification
      - terraform --version
      - aws --version

  build:
    commands:
      # Initialize Terraform (if not already initialized)
      - terraform init -input=false

      # Perform Terraform plan
      - terraform plan -out=tfplan -input=false

  post_build:
    commands:
      # Optionally validate Terraform configuration after plan (optional)
      - terraform validate

artifacts:
  files:
    - tfplan
